-- Up

CREATE TABLE income (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    amount INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL
);


CREATE TABLE expense (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    amount INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL
);